# Generated by Django 2.2.4 on 2022-03-03 07:02

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0003_auto_20220303_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('delivery_company', models.CharField(blank=True, max_length=130, verbose_name='Delivery Company')),
                ('range_date_start', models.DateField(null=True, verbose_name='Date inital')),
                ('range_date_end', models.DateField(null=True, verbose_name='Date end')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Tracking number')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_order_delivery', to='shop.ShopOrder', verbose_name='Shop order')),
            ],
            options={
                'db_table': 'order_delivery',
            },
        ),
    ]
