# Generated by Django 2.2.4 on 2021-08-05 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import panel.config.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=80, verbose_name='App Label')),
                ('title', models.CharField(max_length=120, verbose_name='Título')),
                ('module', models.CharField(blank=True, max_length=120, verbose_name='Módulo')),
                ('url', models.CharField(max_length=120, verbose_name='URL')),
                ('icon', models.CharField(max_length=60, verbose_name='icono')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('has_submenu', models.BooleanField(default=False, verbose_name='Con Submenu')),
                ('is_menu', models.BooleanField(default=True, verbose_name='Es Menú')),
                ('is_module', models.BooleanField(default=True, verbose_name='Es Módulo')),
                ('is_global', models.BooleanField(default=False, verbose_name='Es Global')),
                ('is_store', models.BooleanField(default=False, verbose_name='Es Tienda')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Módulos',
                'verbose_name_plural': 'Módulos',
                'db_table': 'modules_items',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='PanelAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('logo', models.ImageField(upload_to=panel.config.models.get_logo, verbose_name='Logo Login')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Dato',
                'verbose_name_plural': 'Datos',
                'db_table': 'panel_admin',
            },
        ),
        migrations.CreateModel(
            name='TemplateComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('code', models.TextField(verbose_name='Codigo')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'Componentes',
                'db_table': 'template_components',
            },
        ),
        migrations.CreateModel(
            name='ModuleSubItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Título')),
                ('module', models.CharField(default='', max_length=120, verbose_name='Módulo')),
                ('url', models.CharField(max_length=120, verbose_name='URL')),
                ('icon', models.CharField(blank=True, max_length=60, verbose_name='icono')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('is_submenu', models.BooleanField(default=True, verbose_name='Es Submódulo')),
                ('is_store', models.BooleanField(default=False, verbose_name='Es Tienda')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subitems', to='config.ModuleItem', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Sub Módulos',
                'verbose_name_plural': 'Sub Módulos',
                'db_table': 'modules_subitems',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('ip', models.GenericIPAddressField(protocol='IPv4', verbose_name='IP')),
                ('sessionkey', models.CharField(blank=True, max_length=40, verbose_name='Sesión')),
                ('logtype', models.CharField(choices=[('I', 'Info'), ('A', 'Acceso'), ('E', 'Error')], max_length=1, verbose_name='Tipo de Log')),
                ('user_agent', models.CharField(blank=True, max_length=250, verbose_name='Navegador')),
                ('message', models.CharField(blank=True, max_length=200, verbose_name='Mensaje')),
                ('url', models.URLField(verbose_name='URL')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logger', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'db_table': 'users_logs',
                'ordering': ('-created',),
            },
        ),
    ]
