# Generated by Django 2.2.4 on 2022-02-28 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import portal.shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0009_auto_20220228_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('phone', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=200, verbose_name='Correo electrónico')),
                ('comment', models.TextField(verbose_name='Comentario')),
            ],
            options={
                'verbose_name': 'Contacto',
                'db_table': 'contact',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('folio', models.CharField(default=portal.shop.models.folio_order, max_length=30, verbose_name='Order Folio')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('email', models.EmailField(max_length=80, verbose_name='Email')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_orders', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Shop order',
                'db_table': 'shop_orders',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Estado')),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='ShopOrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Quantity')),
                ('size', models.CharField(max_length=8, verbose_name='Size')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='Name')),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_orders', to='shop.ShopOrder', verbose_name='Shop order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_orders', to='products.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order Product',
                'db_table': 'shop_orders_products',
            },
        ),
        migrations.CreateModel(
            name='ShopOrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_folio', models.CharField(max_length=30, verbose_name='Stripe code')),
                ('total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total')),
                ('shipping', models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='Shipping')),
                ('date_payment', models.DateField(auto_now_add=True, verbose_name='Payment date')),
                ('status', models.CharField(choices=[('PE', 'Pendiente'), ('EP', 'En proceso'), ('EE', 'Enviado'), ('EN', 'Entregado')], default='PE', max_length=2)),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_payment', to='products.Coupon')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment', to='shop.ShopOrder', verbose_name='Shop order')),
            ],
            options={
                'verbose_name': 'Order Payment',
                'db_table': 'shop_orders_payments',
            },
        ),
        migrations.CreateModel(
            name='ShopOrderDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=120, verbose_name='Address')),
                ('zip_code', models.CharField(max_length=5, verbose_name='Zip code')),
                ('num_ext', models.CharField(max_length=5, verbose_name='Num Ext')),
                ('num_int', models.CharField(max_length=5, verbose_name='Num Int')),
                ('city', models.CharField(max_length=80, verbose_name='City')),
                ('state', models.CharField(max_length=30, verbose_name='State')),
                ('suburb', models.CharField(max_length=50, verbose_name='Suburb')),
                ('country', models.CharField(default='MX', max_length=80, verbose_name='Country')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_delivery', to='shop.ShopOrder', verbose_name='Shop order')),
            ],
            options={
                'verbose_name': 'Order delivery',
                'db_table': 'shop_orders_delivery',
            },
        ),
    ]
