# Generated by Django 2.2.4 on 2022-03-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoporderpayment',
            name='stripe_folio',
        ),
        migrations.AddField(
            model_name='shoporderpayment',
            name='client_secret',
            field=models.CharField(default='pi_3KZ7FaIKF8Hi9Jx60lH5FB1R_secret_XkYVDQNaMcJQRJXnkTWCcPtvM', max_length=120, verbose_name='Client secret ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoporderpayment',
            name='payment_intent',
            field=models.CharField(default='pi_3KZ7FaIKF8Hi9Jx60lH5FB1R', max_length=100, verbose_name='Payment Intent ID'),
            preserve_default=False,
        ),
    ]
