# Generated by Django 2.2.4 on 2022-03-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220302_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoporderproduct',
            name='size',
            field=models.CharField(max_length=50, verbose_name='Size'),
        ),
    ]
