# Generated by Django 2.2.4 on 2022-03-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20220303_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporderproduct',
            name='name_personalization',
            field=models.CharField(max_length=120, null=True, verbose_name='Name Personalization'),
        ),
    ]
