# Generated by Django 2.2.4 on 2022-04-23 05:58

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shoporderproduct_name_personalization'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporder',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.CreateModel(
            name='ShopOrderCancel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_cancel', to='shop.ShopOrder', verbose_name='Shop order')),
            ],
            options={
                'db_table': 'shop_orders_canceled',
            },
        ),
    ]
