# Generated by Django 2.2.4 on 2022-05-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20220422_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporderpayment',
            name='shipping_method',
            field=models.CharField(default='nacional', max_length=10, verbose_name='Shipping method'),
            preserve_default=False,
        ),
    ]
