# Generated by Django 2.2.4 on 2022-06-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_shoporderpayment_shipping_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporderproduct',
            name='gift',
            field=models.BooleanField(default=False, verbose_name='Gift'),
        ),
    ]
