# Generated by Django 2.2.4 on 2022-07-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_shoporderproduct_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporderpayment',
            name='brand_card',
            field=models.CharField(default='visa', max_length=15, verbose_name='Brand card'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoporderpayment',
            name='last4',
            field=models.CharField(default='4242', max_length=4, verbose_name='last 4 digits'),
            preserve_default=False,
        ),
    ]
