# Generated by Django 2.2.4 on 2022-07-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20220714_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporderpayment',
            name='payment_status',
            field=models.CharField(default='succeded', max_length=50, verbose_name='Payment status'),
            preserve_default=False,
        ),
    ]
