# Generated by Django 2.2.4 on 2022-07-17 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_shoporderpayment_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoporderproduct',
            name='name',
        ),
        migrations.RemoveField(
            model_name='shoporderproduct',
            name='number',
        ),
    ]
