# Generated by Django 2.2.4 on 2022-03-21 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=130, null=True, verbose_name='Name')),
                ('address', models.CharField(max_length=120, verbose_name='Address')),
                ('zip_code', models.CharField(max_length=5, verbose_name='Zip code')),
                ('num_ext', models.CharField(max_length=5, verbose_name='Num Ext')),
                ('num_int', models.CharField(max_length=5, verbose_name='Num Int')),
                ('city', models.CharField(max_length=80, verbose_name='City')),
                ('state', models.CharField(max_length=30, verbose_name='State')),
                ('suburb', models.CharField(max_length=50, verbose_name='Suburb')),
                ('default', models.BooleanField(default=False, verbose_name='Predeterminada')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'db_table': 'address',
                'ordering': ['-created'],
            },
        ),
    ]
