# Generated by Django 2.2.4 on 2022-02-14 05:01

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import panel.core.validators
import panel.products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('slug', models.SlugField(default=None, max_length=120, verbose_name='Slug')),
                ('brand', models.CharField(max_length=30, verbose_name='Brand')),
                ('model', models.CharField(max_length=30, verbose_name='Model')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('aditional', models.TextField(blank=True, null=True, verbose_name='Info Aditional')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Price')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductHexaCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120, verbose_name='Name')),
                ('hexacode', models.CharField(max_length=7, verbose_name='Code')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Hexacode',
                'verbose_name_plural': 'Hexacodes',
                'db_table': 'hexacodes',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Size')),
                ('charge', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Cargo')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
                'db_table': 'sizes',
            },
        ),
        migrations.CreateModel(
            name='ProductHexaCodeM2M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('hexacode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductHexaCode')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hexacodes_m2m', to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('image', models.FileField(upload_to=panel.products.models.get_product_gallery, validators=[panel.core.validators.validate_file_extension], verbose_name='Image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_gallery', to='products.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallery',
                'db_table': 'products_gallery',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='hexacodes',
            field=models.ManyToManyField(related_name='products_hexacode', through='products.ProductHexaCodeM2M', to='products.ProductHexaCode'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(related_name='products_sizes', to='products.ProductSize'),
        ),
    ]
