# Generated by Django 2.2.4 on 2022-02-20 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('margin', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Margin')),
                ('gain', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Gain')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Sale Price')),
                ('is_sale', models.BooleanField(default=False, verbose_name='Sale')),
                ('is_outstanding', models.BooleanField(default=False, verbose_name='Outstanding')),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Shipping to home')),
                ('shipping_free', models.BooleanField(default=False, verbose_name='Shipping Free')),
                ('shipping_min', models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Shipping min')),
                ('has_personalization', models.BooleanField(default=False, verbose_name='Has_personalization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.Product')),
            ],
            options={
                'verbose_name_plural': 'Product properties',
                'db_table': 'product_properties',
            },
        ),
    ]
