# Generated by Django 2.2.4 on 2022-02-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220220_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productproperty',
            old_name='shipping',
            new_name='shipping_price',
        ),
        migrations.RemoveField(
            model_name='productproperty',
            name='price',
        ),
        migrations.AddField(
            model_name='productproperty',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Sell Price'),
        ),
    ]
