# Generated by Django 2.2.4 on 2022-02-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220220_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproperty',
            name='gain',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Gain'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Margin'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Sale Price'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Sell Price'),
        ),
    ]
