# Generated by Django 2.2.4 on 2022-02-25 21:58

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220221_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.CharField(max_length=30, verbose_name='Código')),
                ('discount', models.PositiveSmallIntegerField(verbose_name='Descuento')),
                ('discount_types', models.CharField(choices=[('S', 'Seleccione'), ('P', 'Porcentaje'), ('A', 'Monto')], default='P', max_length=1, verbose_name='Tipos de descuento')),
                ('no_uses', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='No. de usos')),
                ('uses', models.PositiveSmallIntegerField(default=0, verbose_name='Usos')),
                ('apply_all', models.BooleanField(default=False, verbose_name='Apply all products')),
                ('min_purchase', models.PositiveSmallIntegerField(default=0, verbose_name='Minimun purchase')),
                ('date_expiration', models.DateField(default=None, verbose_name='Fecha expiración')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Cupon',
                'verbose_name_plural': 'Cupones',
                'db_table': 'coupons',
            },
        ),
        migrations.CreateModel(
            name='CouponProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_coupons', to='products.Coupon')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_coupons', to='products.Product')),
            ],
            options={
                'db_table': 'products_coupons',
            },
        ),
    ]
