# Generated by Django 2.2.4 on 2022-03-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20220228_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='name',
            field=models.CharField(max_length=35, verbose_name='Size'),
        ),
    ]
