# Generated by Django 2.2.4 on 2022-06-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20220303_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productproperty',
            name='has_personalization',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('X', 'Selecciona...'), ('S', 'Agenda'), ('N', 'Libreta'), ('P', 'Planner'), ('O', 'Organizador')], default='X', max_length=1, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('X', 'Selecciona...'), ('C', 'Personalizable'), ('N', 'No personalizable'), ('S', 'Escolar'), ('D', 'Diaria'), ('W', 'Bodas'), ('P', 'Embarazo')], default='X', max_length=1, verbose_name='Subcategoria'),
        ),
    ]
