# Generated by Django 2.2.4 on 2022-07-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20220603_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('X', 'Selecciona...'), ('S', 'Agenda'), ('N', 'Libreta'), ('P', 'Planner'), ('O', 'Organizador'), ('R', 'Recetario')], default='X', max_length=1, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('X', 'Selecciona...'), ('C', 'Personalizable'), ('N', 'No personalizable'), ('S', 'Escolar'), ('D', 'Diaria'), ('W', 'Bodas'), ('P', 'Embarazo'), ('A', 'No aplica')], default='X', max_length=1, verbose_name='Subcategoria'),
        ),
    ]
