# Generated by Django 2.2.4 on 2021-08-05 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        ('accounts', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodulepermissionaction',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_items', to='config.ModuleItem', verbose_name='Items'),
        ),
        migrations.AddField(
            model_name='usermodulepermissionaction',
            name='menu_subitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions_subitems', to='config.ModuleSubItem', verbose_name='SubItems'),
        ),
        migrations.AddField(
            model_name='usermodulepermissionaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permisssion_actions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_items', to='config.ModuleItem', verbose_name='Items'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='menu_subitems',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_subitems', to='config.ModuleSubItem', verbose_name='SubItems'),
        ),
        migrations.AddField(
            model_name='usermodulepermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permisssion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='usermodulegroupaction',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_group_items', to='config.ModuleItem', verbose_name='Items'),
        ),
        migrations.AddField(
            model_name='usermodulegroupaction',
            name='menu_subitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions_group_subitems', to='config.ModuleSubItem', verbose_name='SubItems'),
        ),
        migrations.AddField(
            model_name='usermodulegroupaction',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_actions', to='accounts.Role', verbose_name='Rol de usuario'),
        ),
        migrations.AddField(
            model_name='usermodulegroup',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_items', to='config.ModuleItem', verbose_name='Items'),
        ),
        migrations.AddField(
            model_name='usermodulegroup',
            name='menu_subitems',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_subitems', to='config.ModuleSubItem', verbose_name='SubItems'),
        ),
        migrations.AddField(
            model_name='usermodulegroup',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='accounts.Role', verbose_name='Rol de usuario'),
        ),
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.ManyToManyField(related_name='user_groups', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.Role', verbose_name='Rol de Usuario'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
